export const TOGGLE_ON = 'TOGGLE_ON';
export const TOGGLE_STRICT = 'TOGGLE_STRICT';
export const SIMON_CLICK = 'SIMON_CLICK'
export const PLAYER_CLICK = 'PLAYER_CLICK'
export const ADD_TO_PLAYER_SERIES = 'ADD_TO_PLAYER_SERIES'
